"""add shows table and update ratings for shows

Revision ID: 0ce6edd5ecdf
Revises: 320a3afb2074
Create Date: 2026-07-15 18:26:52.004147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ce6edd5ecdf'
down_revision: Union[str, Sequence[str], None] = '320a3afb2074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('first_air_year', sa.Integer(), nullable=True),
    sa.Column('poster_path', sa.String(length=255), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('number_of_seasons', sa.Integer(), nullable=True),
    sa.Column('number_of_episodes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shows_id'), 'shows', ['id'], unique=False)
    op.create_index(op.f('ix_shows_tmdb_id'), 'shows', ['tmdb_id'], unique=True)
    op.create_table('show_cast',
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.PrimaryKeyConstraint('show_id', 'person_id')
    )
    op.create_index(op.f('ix_show_cast_person_id'), 'show_cast', ['person_id'], unique=False)
    op.create_index(op.f('ix_show_cast_show_id'), 'show_cast', ['show_id'], unique=False)
    op.create_table('show_genres',
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.PrimaryKeyConstraint('show_id', 'genre_id')
    )
    op.add_column('ratings', sa.Column('show_id', sa.Integer(), nullable=True))
    op.alter_column('ratings', 'movie_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_ratings_show_id'), 'ratings', ['show_id'], unique=False)
    op.create_unique_constraint('uq_user_show_rating', 'ratings', ['user_id', 'show_id'])
    op.create_foreign_key(None, 'ratings', 'shows', ['show_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_constraint('uq_user_show_rating', 'ratings', type_='unique')
    op.drop_index(op.f('ix_ratings_show_id'), table_name='ratings')
    op.alter_column('ratings', 'movie_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('ratings', 'show_id')
    op.drop_table('show_genres')
    op.drop_index(op.f('ix_show_cast_show_id'), table_name='show_cast')
    op.drop_index(op.f('ix_show_cast_person_id'), table_name='show_cast')
    op.drop_table('show_cast')
    op.drop_index(op.f('ix_shows_tmdb_id'), table_name='shows')
    op.drop_index(op.f('ix_shows_id'), table_name='shows')
    op.drop_table('shows')
    # ### end Alembic commands ###
