"""add watch_status table

Revision ID: d2af6344abc3
Revises: 0ce6edd5ecdf
Create Date: 2026-07-15 19:28:16.254253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2af6344abc3'
down_revision: Union[str, Sequence[str], None] = '0ce6edd5ecdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watch_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('show_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('want_to_watch', 'watched')", name='ck_watch_status_valid'),
    sa.CheckConstraint('(movie_id IS NOT NULL AND show_id IS NULL) OR (movie_id IS NULL AND show_id IS NOT NULL)', name='ck_watch_exactly_one_target'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'movie_id', name='uq_user_movie_watch'),
    sa.UniqueConstraint('user_id', 'show_id', name='uq_user_show_watch')
    )
    op.create_index(op.f('ix_watch_status_id'), 'watch_status', ['id'], unique=False)
    op.create_index(op.f('ix_watch_status_movie_id'), 'watch_status', ['movie_id'], unique=False)
    op.create_index(op.f('ix_watch_status_show_id'), 'watch_status', ['show_id'], unique=False)
    op.create_index(op.f('ix_watch_status_user_id'), 'watch_status', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watch_status_user_id'), table_name='watch_status')
    op.drop_index(op.f('ix_watch_status_show_id'), table_name='watch_status')
    op.drop_index(op.f('ix_watch_status_movie_id'), table_name='watch_status')
    op.drop_index(op.f('ix_watch_status_id'), table_name='watch_status')
    op.drop_table('watch_status')
    # ### end Alembic commands ###
